name: App Test

# 1
on:
  # 2
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # 3
  workflow_dispatch:

# 4
jobs:
  test:
  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
       
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.7"
          channel: 'stable'
          
      - name: Get dependencies
        run: flutter pub get
        
      - name: Run tests
        run: flutter test
      
      # Upload test report to the artifacts.
      - uses: actions/upload-artifact@v1
        with:
          name: test-report
          path: coverage/lcov.info
        
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v3
      
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
       
      - uses: subosito/flutter-action@v2
        with:
          
          flutter-version: "3.7.7"
          channel: 'stable'
          
      - name: Get dependencies
        run: flutter pub get
      